-- STAGING MODEL
-- Purpose : Light cleaning — rename, cast types, basic nulls
-- Source  : RAW.CARE_HEALTH
-- Output  : STAGING.STG_CARE_HEALTH
-- Type    : VIEW (no data stored — runs on query)

{{ config(materialized='view') }}

SELECT

    -- Patient name — fix mixed case
    -- "bobby JacksOn" → "Bobby Jackson"
    {{ clean_name('name') }}                            AS patient_name,

    -- Age — cast to integer
    TRY_TO_NUMBER(age)                                  AS age,

    -- Gender — standardize
    {{ clean_string('gender', 'UNKNOWN') }}             AS gender,

    -- Blood type — uppercase
    UPPER(TRIM(blood_type))                             AS blood_type,

    -- Medical condition — title case
    INITCAP(TRIM(medical_condition))                    AS medical_condition,

    -- Parse admission date from string to DATE
    TRY_CAST(date_of_admission AS DATE)                AS date_of_admission,

    -- Parse discharge date from string to DATE
    TRY_CAST(discharge_date AS DATE)                   AS discharge_date,

    -- Doctor name — title case
    INITCAP(TRIM(doctor))                               AS doctor_name,

    -- Hospital name — title case
    INITCAP(TRIM(hospital))                             AS hospital_name,

    -- Insurance provider — standardize
    {{ clean_string('insurance_provider', 'UNKNOWN') }} AS insurance_provider,

    -- Billing amount — cast to float
    TRY_TO_DOUBLE(billing_amount)                       AS billing_amount,

    -- Room number
    TRIM(room_number)                                   AS room_number,

    -- Admission type — standardize
    {{ clean_string('admission_type', 'UNKNOWN') }}     AS admission_type,

    -- Medication — title case
    INITCAP(TRIM(medication))                           AS medication,

    -- Test results — standardize
    {{ clean_string('test_results', 'UNKNOWN') }}       AS test_results,

    -- Audit columns
    -- Audit columns (generated by DBT — not from source table)
    CURRENT_TIMESTAMP()  AS load_date,
    'RAW.CARE_HEALTH'    AS source_file

FROM {{ source('raw', 'care_health') }}
WHERE name IS NOT NULL
AND   TRIM(name) != ''